#add stages here  
stages:
  prepare_data:
    cmd: python src/stage1.py --config=configs/config.yaml --params=params.yaml
    deps:
    - src/stage1.py
    - data/data.xml
    - src/utils/common.py
    - src/utils/data_mgmt.py
    - configs/config.yaml

    params:
      - prepare.seed
      - prepare.split
    outs:
    - artifacts/prepared/train.tsv
    - artifacts/prepared/test.tsv


  featurize:
    cmd: python src/stage2.py --config=configs/config.yaml --params=params.yaml
    deps:
    - src/stage2.py
    - artifacts/prepared/train.tsv
    - artifacts/prepared/test.tsv
    - src/utils/featurize.py
    - src/utils/common.py
    - src/utils/data_mgmt.py
    - configs/config.yaml

    params:
      - featurize.max_params
      - featurize.ngrams
    outs:
    - artifacts/features/train.pkl
    - artifacts/features/test.pkl



  training:
    cmd: python src/stage3.py --config=configs/config.yaml --params=params.yaml
    deps:
    - src/stage3.py
    
    - artifacts/features/train.pkl
    
    
    - src/utils/common.py
    
    - configs/config.yaml

    params:
      - train.seed
      - train.n_est
    
      - train.min_split
      
    outs:
    - artifacts/model/model.pkl



  evaluate:
    cmd: python src/stage4.py --config=configs/config.yaml
    deps:
      - src/stage4.py
      - artifacts/features/test.pkl
      - src/utils/common.py
      - configs/config.yaml
      - artifacts/model/model.pkl
    metrics:
      - scores.json:
          cache: false
    plots:
      - prc.json:
          cache: false
          x: recall
          y: precision
      - roc.json:
          cache: false
          x: fpr
          y: tpr

  run_plots_command:
    cmd: dvc plots diff
    
